name: Self-Hosted Runner Test

# START OF COMMON SECTION
on:
  push:
    branches:
      - ED25519_SHA2_fix
# END OF COMMON SECTION

jobs:
  test:
    # Don't run this on downstream forks:
    if: github.repository_owner == 'gojimmypi'
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          echo "apt-get install shellcheck"
          ls /mnt/c/SysGCC

      - name: Run tests
        run: |
          whoami
