name: Self-Hosted Runner Test

on:
  push:
    branches:
      - ED25519_SHA2_fix

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust according to your project setup

      - name: Run tests
        run: |
          # Your test command here, e.g., pytest
          pytest
